trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
    yarn install
  displayName: 'Install Dependencies'

- script: |
    cd android
    ./gradlew clean
    ./gradlew assembleRelease
  displayName: 'Build Android Release'

- task: CopyFiles@2
  inputs:
    contents: 'android/app/build/outputs/apk/release/app-release.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy APK to Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish APK as Build Artifact'
